-- Salesforce integration: outbox + columnas de linking en leads/affiliates.
--
-- `sf_messages` es el outbox de cada envío a SF (/leads, /sales, /copayments).
-- El código del portal INSERTA una fila antes del POST a SF (idempotencia por
-- message_id UNIQUE) y UPDATEa la respuesta cuando llega. Si el INSERT falla,
-- el POST a SF no se dispara. Ver src/lib/salesforce/{leads,sales,copayments}.ts.
--
-- `sf_lead_id` / `sf_account_id` / `sf_account_code` guardan los IDs que SF
-- devuelve en los acks, para que envíos sucesivos reusen el mismo Prospect/Account
-- en SF en vez de crear duplicados.

create table if not exists public.sf_messages (
  id             bigint generated by default as identity primary key,
  message_id     uuid not null unique,
  endpoint       text not null,
  lead_id        uuid references public.leads(id) on delete set null,
  affiliate_id   uuid references public.affiliates(id) on delete set null,
  request_body   jsonb not null,
  response_status integer,
  response_body  jsonb,
  responded_at   timestamptz,
  created_at     timestamptz not null default now()
);

create index if not exists sf_messages_lead_id_idx on public.sf_messages(lead_id);
create index if not exists sf_messages_affiliate_id_idx on public.sf_messages(affiliate_id);
create index if not exists sf_messages_created_at_idx on public.sf_messages(created_at desc);

alter table public.leads
  add column if not exists sf_lead_id text;

alter table public.affiliates
  add column if not exists sf_lead_id text,
  add column if not exists sf_account_id text,
  add column if not exists sf_account_code text;
